### ISSUE TITLE
it can not work for "react": "15.2.0", "react-native": "0.28.0"

### ISSUE THREAD

**Issue by vivianking6855** [apentle/react-native-theme#1]
it can not work for "react": "15.2.0", "react-native": "0.28.0"

**Comment by doanndd** [comment]
I have used "react": "15.2.0", "react-native": "0.28.0" for my example: https://github.com/apentle/react-native-theme-example. It works well with "react-native-theme": "0.1.1". Hope this example is helpful for your issue.
